CREATE TABLE PRODUCT (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    PRICE FLOAT NOT NULL,
    DESCRIPTION VARCHAR(200),
    STOCK INTEGER NOT NULL,
    IMAGE VARCHAR(200) NOT NULL,
    BRAND_ID INTEGER,
    FOREIGN KEY (BRAND_ID) REFERENCES BRAND (ID)
)

CREATE TABLE BRAND (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(50)
)

CREATE TABLE SEASON (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    DESCRIPTION VARCHAR(200),
    STATUS CHAR(1) NOT NULL
)

CREATE TABLE SEASON_PRODUCT (
    PRODUCT_ID INTEGER NOT NULL,
    SEASON_ID INTEGER NOT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID),
    FOREIGN KEY (SEASON_ID) REFERENCES SEASON (ID)
)

CREATE TABLE CATEGORY (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PARENT_CATEGORY_ID INTEGER,
    FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES CATEGORY (ID)
)

CREATE TABLE CATEGORY_PRODUCT (
    CATEGORY_ID INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
)

CREATE TABLE CUSTOMER (
    ID INTEGER PRIMARY KEY,
    NAMES VARCHAR(100) NOT NULL,
    LAST_NAMES VARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(8) NOT NULL,
    ADDRESS VARCHAR(200) NOT NULL,
    STATUS CHAR(1) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL
)


CREATE TABLE CREDIT_CARD (
    ID INTEGER PRIMARY KEY,
    TYPE VARCHAR (100) NOT NULL,
    CC_NUMBER VARCHAR(200) NOT NULL,
    CC_DUE_DATE DATE NOT NULL,
    CC_NAME VARCHAR(50) NOT NULL,
    STATUS CHAR(1) NOT NULL,
    CUSTOMER_ID INTEGER NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
)

CREATE TABLE "ORDER" (
    ID INTEGER PRIMARY KEY,
    PURCHASE_DATE DATE NOT NULL,
    CUSTOMER_ID INTEGER NOT NULL,
    TOTAL FLOAT NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
)

CREATE TABLE ORDER_DETAIL (
    ORDER_ID INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    QTY INTEGER NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES "ORDER" (ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
)